apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  labels:
    app: delivery-service
spec:
  selector:
    app: delivery-service
  ports:
    - protocol: TCP
      port: 7004
      targetPort: 7004
  type: ClusterIP
